export interface TranslationFailure {
    message: string;
    code: string;
    status?: number;
}
/** Translation history identity generated by the Host. */
export type TranslationHistoryId = string;
/** JSON-safe provider/model route used by the translation wire. */
export interface TranslationModelSelection {
    provider: string;
    model: string;
    reasoningEffort?: string;
}
export interface TranslationRequest {
    sourceLanguage: string;
    targetLanguage: string;
    text: string;
    selection: TranslationModelSelection;
}
export interface TranslationStartResult {
    jobId: string;
}
export interface TranslationJobView {
    jobId: string;
    status: 'running' | 'completed' | 'cancelled' | 'error';
    output: string;
    selection: TranslationModelSelection;
    sourceLanguage: string;
    targetLanguage: string;
    createdAt: number;
    updatedAt: number;
    failure?: TranslationFailure;
    historyId?: TranslationHistoryId;
}
export interface TranslationHistoryItem {
    id: TranslationHistoryId;
    sourceLanguage: string;
    targetLanguage: string;
    sourceText: string;
    translatedText: string;
    selection: TranslationModelSelection;
    /** Starred (favorited) so the history panel can filter to favorites. */
    starred: boolean;
    createdAt: number;
}
export interface TranslationHistoryPage {
    items: TranslationHistoryItem[];
    nextCursor?: string;
}
export interface TranslationLanguage {
    id: string;
    label: string;
    builtin: boolean;
}
export interface TranslationLanguagesView {
    source: TranslationLanguage[];
    target: TranslationLanguage[];
}
declare module '@deepseek-ai/dsh-typert-protocol' {
    interface TypertRemoteNamespaceMap {
        controlCenterTranslation: {
            start(request: TranslationRequest): Promise<{
                ok: true;
                value: TranslationStartResult;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            get(jobId: string): Promise<{
                ok: true;
                value: TranslationJobView;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            cancel(jobId: string): Promise<{
                ok: true;
                value: TranslationJobView;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            history(cursor: string | null, limit: number): Promise<{
                ok: true;
                value: TranslationHistoryPage;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            deleteHistory(id: TranslationHistoryId): Promise<{
                ok: true;
                value: {
                    absent: true;
                };
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            starHistory(id: TranslationHistoryId, starred: boolean): Promise<{
                ok: true;
                value: TranslationHistoryItem;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            clearHistory(): Promise<{
                ok: true;
                value: {
                    cleared: number;
                };
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            /** Current custom translation prompt override (empty = built-in prompt). */
            getPrompt(): Promise<{
                ok: true;
                value: string;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            setPrompt(prompt: string): Promise<{
                ok: true;
                value: {
                    saved: true;
                };
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            languages(): Promise<{
                ok: true;
                value: TranslationLanguagesView;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            putLanguage(id: string, label: string): Promise<{
                ok: true;
                value: TranslationLanguage;
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
            deleteLanguage(id: string): Promise<{
                ok: true;
                value: {
                    absent: true;
                };
            } | {
                ok: false;
                error: {
                    code: string;
                    message: string;
                    details: object;
                };
            }>;
        };
    }
}
//# sourceMappingURL=translation-types.d.ts.map