/**
 * Cherry Studio painting prompt templates — generated by
 * build/build-painting-templates.mjs from vendor/painting-templates
 * (catalog.json + locales/zh-cn.json + images/*.webp, downscaled 240px).
 * AGPL-3.0-only; adapted from Cherry Studio resources (see provenance).
 * Do not edit by hand.
 */
export interface PaintingTemplate {
    id: string;
    label: string;
    prompt: string;
    /** Downscaled webp preview as a data URI. */
    image: string;
}
export declare const PAINTING_TEMPLATES: readonly PaintingTemplate[];
//# sourceMappingURL=painting-templates-data.d.ts.map