/**
 * Cherry provider icon glyphs — generated by build/build-provider-icons.mjs
 * from cherry-studio packages/ui/src/components/icons/providers/<id>/light.tsx
 * (JSX normalized to plain HTML). AGPL-3.0-only; see provenance. Do not edit.
 */
export interface ProviderIconGlyph {
    key: string;
    viewBox: string;
    body: string;
    color: string;
}
export declare const PROVIDER_ICONS: readonly ProviderIconGlyph[];
export declare function providerIcon(id: string): ProviderIconGlyph | undefined;
export declare function providerIconSvg(id: string, size?: number): string;
//# sourceMappingURL=provider-icons-data.d.ts.map